### PR TITLE
Disable Jetifier

### PR DESCRIPTION
**Pull request by FranAguilarRod**
I want to disable Jetifier on my project but you still have a dependency using the support.

Dexter migrate to androidX on their 6.0.0 release: https://github.com/Karumi/Dexter/releases/tag/6.0.0

Thanks!

### CODE REVIEW

**Comment by franciscofranco** [comment]
Any timeline to merge this? We're having this same issue.

**Comment by mrebollob** [comment]
Hi @FranAguilarRod! Thanks for the PR. I will merge it in the `develop` branch and include it in the next release

**Comment by franciscofranco** [comment]
Sorry for pestering - is this planned to be released eventually?

**Comment by CesarTrigo** [comment]
Hi @franciscofranco
Apologies for the delay but we are about to release it this week. The final testing is taking place "as we speak". I will keep you posted.

**Comment by franciscofranco** [comment]
> Hi @franciscofranco
> Apologies for the delay but we are about to release it this week. The final testing is taking place "as we speak". I will keep you posted.

Thank you so much!

**Comment by CesarTrigo** [comment]
Hi @FranAguilarRod  and @franciscofranco 
As mentioned, this PR has been included in version [v3.2.2](https://github.com/applivery/applivery-android-sdk/releases/tag/v3.2.2) released yesterday.

Thank you for your contributions
C.

**Comment by franciscofranco** [comment]
Thank you so much!

**Pull request merged**
